[package]
name = "assert_unordered"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[features]
default = ["std"]
std = []

[dependencies]
